print("O jeito difícil...")
print("##############################")
print("##############################")
print("##############################")
print("O jeito fácil...")
print("#"*30)
print("#"*30)
print("#"*30)
print("")
print("/\  "*10)
print("  \/"*10)